// ─────────────────────────────────────────────────────────────
// src/indexGen.js — Creates the master notes/README.md index
// that links to every generated note file.
// ─────────────────────────────────────────────────────────────

const fs   = require('fs');
const path = require('path');

/**
 * Generates notes/README.md — a master index of all note files.
 *
 * @param {string}   repoPath  - Root path of the repo
 * @param {Array}    noteFiles - Array of note metadata from notesGen.js
 * @param {string}   repoUrl   - Original GitHub URL (for display)
 */
async function generateIndex(repoPath, noteFiles, repoUrl) {
  // extract repo name from URL for the title
  const repoName = repoUrl
    .split('/')
    .pop()
    .replace(/\.git$/, '');

  // get current date for the header
  const date = new Date().toLocaleDateString('en-GB', {
    day: 'numeric', month: 'long', year: 'numeric'
  });

  // ── Build the markdown content ─────────────────────────────
  let md = '';

  // header
  md += `# 📚 Study Notes — ${repoName}\n\n`;
  md += `> Auto-generated by [repo-auto-editor](https://github.com/Dasmat13/repo-auto-ediitor) on ${date}\n\n`;
  md += `---\n\n`;

  // summary stats
  md += `## 📊 Summary\n\n`;
  md += `| Stat | Value |\n`;
  md += `|------|-------|\n`;
  md += `| Total files annotated | ${noteFiles.length} |\n`;

  // count languages
  const langCount = {};
  for (const n of noteFiles) {
    langCount[n.language] = (langCount[n.language] || 0) + 1;
  }
  for (const [lang, count] of Object.entries(langCount)) {
    md += `| ${lang} files | ${count} |\n`;
  }

  md += `\n---\n\n`;

  // ── Notes index table ──────────────────────────────────────
  md += `## 📂 Notes Index\n\n`;
  md += `| Note File | Source File | Language |\n`;
  md += `|-----------|-------------|----------|\n`;

  for (const note of noteFiles) {
    // create relative link from notes/README.md to each note file
    const noteLink = `[${note.fileName}](./${note.fileName})`;
    md += `| ${noteLink} | \`${note.sourceFile}\` | ${note.language} |\n`;
  }

  md += `\n---\n\n`;

  // ── Quick cheat sheet reminder ─────────────────────────────
  md += `## 💡 How to Use These Notes\n\n`;
  md += `1. **Open a source file** — read it top to bottom (comments explain every line)\n`;
  md += `2. **Run it** — \`node filename.js\` or equivalent for your language\n`;
  md += `3. **Open its note file** — review key concepts, bugs, and interview Q&A\n`;
  md += `4. **Test yourself** — try answering the interview questions before reading the answers\n\n`;
  md += `---\n\n`;
  md += `*Generated by [repo-auto-editor](https://github.com/Dasmat13/repo-auto-ediitor) · Powered by Gemini AI*\n`;

  // ── Write the file ─────────────────────────────────────────
  const notesDir  = path.join(repoPath, 'notes');
  const indexPath = path.join(notesDir, 'README.md');

  // create notes dir if it doesn't exist yet
  if (!fs.existsSync(notesDir)) {
    fs.mkdirSync(notesDir, { recursive: true });
  }

  fs.writeFileSync(indexPath, md, 'utf8');
}

module.exports = { generateIndex };
